### ISSUE TITLE
Make use of expires_in from servant-spotify TokenResponse

### ISSUE THREAD

**Issue by chances** [chances/chances-party#12]
Make use of [expires_in](https://github.com/chances/servant-spotify/blob/master/src/Network/Spotify/Api/Types.hs#L187) from servant-spotify TokenResponse.

[Auth.hs `callback`](https://github.com/chances/chances-party/blob/master/src/Api/Auth.hs#L176)

Probably just store it in the DB with the User model next to the tokens?

Should the server automatically refresh the token? Should the server notify its applicable clients (via a WebSocket, if available for the client) when this happens?

_Note: WebSocket clients would then need to be labelled with its associated session in metadata._

----

### Tasks

- [x] Add expires_in to the User model
- [ ] Automatically refresh the access token
- [ ] Notify WebSocket clients that belong to the same session using the expired token?

**Comment by chances** [comment]
Added token expiry date to User model and integrated into a new `/auth/token` endpoint (https://github.com/chances/chances-party/commit/da74012a2b6e701ef4e8045967b7dd4e1ecb15dd).

**Comment by chances** [comment]
This issue is now invalid: [zmb3/spotify](https://github.com/zmb3/spotify) automatically refreshes access tokens.
